<?php
namespace Ronu\LaravelFederatedAuth\Providers;
use Firebase\JWT\JWK; use Firebase\JWT\JWT; use GuzzleHttp\Client; use GuzzleHttp\ClientInterface; use Ronu\LaravelFederatedAuth\Contracts\IdentityProviderAdapterInterface; use Ronu\LaravelFederatedAuth\DTO\AuthContext; use Ronu\LaravelFederatedAuth\DTO\ExternalIdentity; use Ronu\LaravelFederatedAuth\Exceptions\InvalidOidcTokenException; use Ronu\LaravelFederatedAuth\Support\ClaimReader; use Ronu\LaravelFederatedAuth\Support\ProviderConfig;
class GenericOidcProviderAdapter implements IdentityProviderAdapterInterface { public function __construct(private readonly ?ClientInterface $http=null){} public function name(): string { return 'oidc'; } public function supports(string $provider): bool { $cfg=config("federated-auth.providers.$provider"); return is_array($cfg)&&($cfg['driver']??null)==='oidc'; } public function redirectUrl(AuthContext $context): string { $cfg=ProviderConfig::get($context->provider); if(empty($cfg['authorization_endpoint'])) throw new InvalidOidcTokenException('OIDC authorization_endpoint is missing.'); return $cfg['authorization_endpoint'].'?'.http_build_query(['client_id'=>$cfg['client_id'],'redirect_uri'=>$context->redirectUri?:$cfg['redirect_uri'],'response_type'=>'code','scope'=>implode(' ',$cfg['scopes']??['openid','profile','email']),'state'=>$context->state?:bin2hex(random_bytes(16))]); } public function userFromCallback(AuthContext $context): ExternalIdentity { $req=$context->request; $code=$req?->query('code')??$req?->input('code'); if(!$code) throw new InvalidOidcTokenException('OIDC callback did not include an authorization code.'); $cfg=ProviderConfig::get($context->provider); $res=$this->client()->post($cfg['token_endpoint'],['form_params'=>['grant_type'=>'authorization_code','client_id'=>$cfg['client_id'],'client_secret'=>$cfg['client_secret']??null,'redirect_uri'=>$context->redirectUri?:$cfg['redirect_uri'],'code'=>$code]]); return $this->identityFromTokenPayload($context->provider,json_decode((string)$res->getBody(),true)?:[],$cfg); } public function userFromToken(string $token,AuthContext $context): ExternalIdentity { $cfg=ProviderConfig::get($context->provider); if(!empty($cfg['userinfo_endpoint'])){ $res=$this->client()->get($cfg['userinfo_endpoint'],['headers'=>['Authorization'=>'Bearer '.$token]]); return $this->identityFromClaims($context->provider,json_decode((string)$res->getBody(),true)?:[],['access_token'=>$token],$cfg); } return $this->identityFromTokenPayload($context->provider,['id_token'=>$token],$cfg); }
 protected function identityFromTokenPayload(string $provider,array $payload,array $cfg): ExternalIdentity { $claims=[]; if(!empty($payload['id_token'])) $claims=$this->decodeIdToken($payload['id_token'],$cfg); if(!$claims&&!empty($payload['access_token'])&&!empty($cfg['userinfo_endpoint'])){ $res=$this->client()->get($cfg['userinfo_endpoint'],['headers'=>['Authorization'=>'Bearer '.$payload['access_token']]]); $claims=json_decode((string)$res->getBody(),true)?:[]; } return $this->identityFromClaims($provider,$claims,$payload,$cfg); }
 protected function identityFromClaims(string $provider,array $claims,array $payload,array $cfg): ExternalIdentity { $sub=(string)($claims['sub']??$claims['id']??''); if($sub==='') throw new InvalidOidcTokenException('OIDC identity does not contain a sub claim.'); return new ExternalIdentity($provider,$sub,$claims['email']??null,(bool)($claims['email_verified']??false),$claims['name']??$claims['preferred_username']??null,$claims['given_name']??null,$claims['family_name']??null,$claims['picture']??null,$claims,$claims,ClaimReader::list($claims,$cfg['groups_claim']??'groups'),ClaimReader::list($claims,$cfg['roles_claim']??'roles'),$payload['access_token']??null,$payload['refresh_token']??null,isset($payload['expires_in'])?(int)$payload['expires_in']:null); }
 protected function decodeIdToken(string $idToken,array $cfg): array { if(empty($cfg['jwks_uri'])) throw new InvalidOidcTokenException('Cannot validate id_token because jwks_uri is missing.'); $jwks=cache()->remember('federated-auth:jwks:'.md5($cfg['jwks_uri']),now()->addMinutes(10),function()use($cfg){ $res=$this->client()->get($cfg['jwks_uri']); return json_decode((string)$res->getBody(),true)?:[]; }); $keys=JWK::parseKeySet($jwks); $decoded=(array)JWT::decode($idToken,$keys); $claims=json_decode(json_encode($decoded),true)?:[]; if(!empty($cfg['issuer'])&&($claims['iss']??null)!==$cfg['issuer']) throw new InvalidOidcTokenException('OIDC issuer validation failed.'); if(!empty($cfg['client_id'])){ $aud=$claims['aud']??null; $audiences=is_array($aud)?$aud:[$aud]; if(!in_array($cfg['client_id'],$audiences,true)) throw new InvalidOidcTokenException('OIDC audience validation failed.'); } return $claims; }
 protected function client(): ClientInterface { return $this->http?:new Client(['timeout'=>10]); }
}
