<?php
namespace Ronu\LaravelFederatedAuth\Repositories;
use Illuminate\Support\Facades\Crypt; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Ronu\LaravelFederatedAuth\Contracts\IdentityLinkRepositoryInterface; use Ronu\LaravelFederatedAuth\DTO\AuthContext; use Ronu\LaravelFederatedAuth\DTO\ExternalIdentity; use Ronu\LaravelFederatedAuth\DTO\LinkedIdentity;
class DatabaseIdentityLinkRepository implements IdentityLinkRepositoryInterface {
 public function findByProviderIdentity(string $provider,string $providerUserId,AuthContext $context): ?LinkedIdentity { $row=$this->baseQuery($context)->where('provider',$provider)->where('provider_user_id',$providerUserId)->first(); return $row?$this->toLinkedIdentity($row):null; }
 public function findByUserAndProvider(string|int $userId,string $provider,AuthContext $context): ?LinkedIdentity { $row=$this->baseQuery($context)->where($this->userIdColumn(),(string)$userId)->where('provider',$provider)->first(); return $row?$this->toLinkedIdentity($row):null; }
 public function create(string|int $userId,ExternalIdentity $identity,AuthContext $context): LinkedIdentity { $now=now(); $payload=['uuid'=>(string)Str::uuid(),$this->userIdColumn()=>(string)$userId,'provider'=>$identity->provider,'provider_user_id'=>$identity->providerUserId,'provider_email'=>$identity->email,'provider_email_verified'=>$identity->emailVerified,'provider_name'=>$identity->name,'provider_avatar'=>$identity->avatarUrl,'claims'=>$this->json($identity->claims),'metadata'=>$this->json($context->metadata),'last_login_at'=>$now,'created_at'=>$now,'updated_at'=>$now]; if($context->tenantId!==null) $payload['tenant_id']=$context->tenantId; if(config('federated-auth.identity_store.store_provider_tokens',false)){ $payload['access_token']=$this->maybeEncrypt($identity->accessToken); $payload['refresh_token']=$this->maybeEncrypt($identity->refreshToken); $payload['token_expires_at']=$identity->expiresIn?now()->addSeconds($identity->expiresIn):null; } $id=$this->table()->insertGetId($payload); return new LinkedIdentity($id,$userId,$identity->provider,$identity->providerUserId,$context->tenantId,$payload); }
 public function touch(LinkedIdentity $linkedIdentity,ExternalIdentity $identity,AuthContext $context): void { $payload=['provider_email'=>$identity->email,'provider_email_verified'=>$identity->emailVerified,'provider_name'=>$identity->name,'provider_avatar'=>$identity->avatarUrl,'claims'=>$this->json($identity->claims),'metadata'=>$this->json($context->metadata),'last_login_at'=>now(),'updated_at'=>now()]; if(config('federated-auth.identity_store.store_provider_tokens',false)){ $payload['access_token']=$this->maybeEncrypt($identity->accessToken); $payload['refresh_token']=$this->maybeEncrypt($identity->refreshToken); $payload['token_expires_at']=$identity->expiresIn?now()->addSeconds($identity->expiresIn):null; } $this->baseQuery($context)->where('id',$linkedIdentity->id)->update($payload); }
 public function delete(LinkedIdentity $linkedIdentity,AuthContext $context): void { $this->baseQuery($context)->where('id',$linkedIdentity->id)->delete(); }
 public function countForUser(string|int $userId,AuthContext $context): int { return $this->baseQuery($context)->where($this->userIdColumn(),(string)$userId)->count(); }
 private function table(){ return DB::connection(config('federated-auth.identity_store.connection'))->table(config('federated-auth.identity_store.table','federated_auth_identities')); }
 private function baseQuery(AuthContext $context){ $q=$this->table(); $tenantColumn=config('federated-auth.identity_store.tenant_column','tenant_id'); if($tenantColumn&&$context->tenantId!==null) $q->where($tenantColumn,$context->tenantId); return $q; }
 private function userIdColumn(): string { return config('federated-auth.identity_store.user_id_column','user_id'); }
 private function toLinkedIdentity(object $row): LinkedIdentity { return new LinkedIdentity($row->id,$row->{$this->userIdColumn()},$row->provider,$row->provider_user_id,$row->tenant_id??null,(array)$row); }
 private function json(array $value): string { return json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?: '{}'; }
 private function maybeEncrypt(?string $value): ?string { if($value===null) return null; return config('federated-auth.identity_store.encrypt_provider_tokens',true)?Crypt::encryptString($value):$value; }
}
